spring:
  config:
    activate:
      on-profile: prod  # Only applies if PROD profile is active

build:
  version: "2.0"

cards:
  message: "prod ap1"
  contacts:
    name1: "prod-name1"
    name2: "prod-name2"
  support:
    - "999999"
    - "888888"
